version: "3.8"

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: auth-postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - auth-network

  # Redis для сессий и кэша
  redis:
    image: redis:7-alpine
    container_name: auth-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - auth-network

  # Backend API Service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: auth-backend
    environment:
      NODE_ENV: development
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: postgres
      PGPASSWORD: 123456
      PGDATABASE: auth_db
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SESSION_SECRET: your-super-secret-key
      JWT_SECRET: your-super-secret-jwt-key
      JWT_REFRESH_SECRET: your-super-secret-refresh-key
      ACCESS_TOKEN_EXPIRY: 15m
      REFRESH_TOKEN_EXPIRY: 7d
      EMAIL_HOST: smtp.gmail.com
      EMAIL_PORT: 587
      EMAIL_USER: your-email@gmail.com
      EMAIL_PASS: your-app-password
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}
      GOOGLE_CALLBACK_URL: ${GOOGLE_CALLBACK_URL}
      CORS_ORIGINS: http://localhost,http://localhost:80,http://localhost:5173
      ENABLE_2FA: false
      ENABLE_EMAIL_VERIFICATION: false
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    networks:
      - auth-network
    volumes:
      - ./backend:/app

  # Frontend Service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: auth-frontend
    environment:
      VITE_API_URL: http://localhost:3000
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - auth-network
    volumes:
      - ./frontend:/usr/share/nginx/html

volumes:
  postgres_data:
  redis_data:

networks:
  auth-network:
