apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-service-config
  namespace: auth-service
data:
  NODE_ENV: "production"
  PGHOST: "postgres-service"
  PGPORT: "5432"
  PGDATABASE: "auth_db"
  REDIS_HOST: "redis-service"
  REDIS_PORT: "6379"
  SESSION_SECRET: "your-super-secret-key-change-in-production"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_USER: "your-email@gmail.com"
  EMAIL_PASS: "your-app-password"
